library(arules)
library(arulesViz)
library(readxl)
library(knitr)
library(ggplot2)
library(lubridate)
library(plyr)
#retail <- read_excel('D:/Online_Retail.xlsx')
wisuda <- read_excel('C:/Users/Florecita/Documents/SKRIPSI/DaWis.xlsx')
#retail <- retail[complete.cases(retail),]
wisuda <- wisuda[complete.cases(wisuda), ]
install.packages("plyr")
library(dplyr)
wisuda %>% mutate(Description = as.factor(Description))
rlang::last_error()
rlang::last_trace()
#library(dlpyr)
#install.packages("plyr")
#library(plyr)
#library(dplyr)